name: Build ANGLE
on:
  - pull_request
  - push

jobs:
  build-angle:
    name: ${{matrix.arch}}-${{matrix.os}}-${{matrix.config}}
    runs-on: ${{matrix.environment}}
    strategy:
      matrix:
        include:
          - os: windows
            arch: x64
            environment: windows-2019
            config: Release

          - os: windows
            arch: x64
            environment: windows-2019
            config: Debug

          - os: linux
            arch: x64
            environment: ubuntu-18.04
            config: Release

          - os: osx
            arch: x64
            environment: macos-10.15
            config: Release

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v2
      with:
        vcpkgArguments: zlib
        vcpkgTriplet: ${{matrix.arch}}-${{matrix.os}}
        vcpkgDirectory: ${{runner.workspace}}/b/vcpkg
        vcpkgGitCommitId: 0591528cbfde14ccfd3900c3fb19aba382c05349

    - name: CMake
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        useVcpkgToolchainFile: true
        configurationRegexFilter: ${{matrix.arch}}-${{matrix.config}}
