name: Build ANGLE
on:
  - pull_request
  - push

jobs:
  build-angle:
    name: ${{matrix.arch}}-${{matrix.os}}-${{matrix.buildType}}
    runs-on: ${{matrix.environment}}

    env:
      vcpkgResponseFile: ${{github.workspace}}/vcpkg-dependencies

    strategy:
      matrix:
        os: [windows, linux, osx]
        arch: [x64]
        buildType: [RelWithDebInfo]

        include:
          - os: windows
            arch: x64
            environment: windows-2019
            buildType: RelWithDebInfo

          - os: windows
            arch: x64
            environment: windows-2019
            buildType: Debug

          - os: linux
            arch: x64
            environment: ubuntu-18.04
            buildType: RelWithDebInfo

          - os: osx
            arch: x64
            environment: macos-latest
            buildType: RelWithDebInfo

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
            submodules: true

      - name: Install Ubuntu packages
        run: sudo apt-get install libgl1-mesa-dev libx11-dev
        if: ${{startsWith(matrix.environment, 'ubuntu')}}

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v2
        with:
          vcpkgTriplet: ${{matrix.arch}}-${{matrix.os}}
          vcpkgArguments: '@${{env.vcpkgResponseFile}}'
          vcpkgDirectory: ${{github.workspace}}/vcpkg
          # Since the cache must be invalidated when content of the response file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{hashFiles(env.vcpkgResponseFile)}}

      - name: Check GL version
        run: glxinfo
        if: ${{startsWith(matrix.environment, 'ubuntu')}}

      - name: CMake
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          buildDirectory: ${{runner.workspace}}/cmake-build
          cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=${{matrix.buildType}} '
