name: Build ANGLE
on:
  - pull_request
  - push

jobs:
  build-angle:
    name: ${{matrix.arch}}-${{matrix.os}}-${{matrix.config}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        config: [Release]
        arch: [x64]

        include:
          - os: windows
            config: Debug
            arch: x64

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v2
      with:
        vcpkgArguments: zlib
        vcpkgTriplet: ${{matrix.arch}}-${{matrix.os}}
        vcpkgDirectory: ${{runner.workspace}}/b/vcpkg
        vcpkgGitCommitId: 0591528cbfde14ccfd3900c3fb19aba382c05349

    - name: CMake
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        useVcpkgToolchainFile: true
        configurationRegexFilter: ${{matrix.arch}}-${{matrix.config}}
