name: Build android.opengl
on:
  - pull_request
  - push

jobs:
  build:
    name: Build ${{matrix.arch}}-${{matrix.os}}-${{matrix.buildType}}
    runs-on: ${{matrix.environment}}

    env:
      vcpkgResponseFile: ${{github.workspace}}/vcpkg-dependencies

    strategy:
      fail-fast: false
      matrix:
        os: [windows, linux, osx]
        arch: [x64]
        buildType: [Release]
        javaVersion: [8]                    # Earliest supported JDK version.

        include:
          - os: windows
            arch: x64
            environment: windows-2019
            buildType: Release
            javaVersion: 8
            uploadArtifact: true
            soPrefix: ''
            soExtension: dll

          - os: windows
            arch: x64
            environment: windows-2019
            buildType: Debug
            javaVersion: 8
            soPrefix: ''
            soExtension: dll
            
          - os: linux
            arch: x64
            environment: ubuntu-18.04
            buildType: Release
            javaVersion: 8
            uploadArtifact: true
            displayWrapper: xvfb-run
            soPrefix: lib
            soExtension: so

          - os: osx
            arch: x64
            environment: macos-latest
            buildType: Release
            javaVersion: 8
            uploadArtifact: true
            soPrefix: lib
            soExtension: dylib

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
            submodules: true

      # Would also install these Ubuntu if they weren't installed by other steps: cmake, ninja-build
      - name: Set up Ubuntu packages
        run: sudo apt-get install curl libgl1-mesa-dev libx11-dev xvfb 
        if: ${{startsWith(matrix.environment, 'ubuntu')}}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.javaVersion}}
          architecture: ${{matrix.arch}}

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v2
        with:
          vcpkgTriplet: ${{matrix.arch}}-${{matrix.os}}
          vcpkgArguments: '@${{env.vcpkgResponseFile}}'
          vcpkgDirectory: ${{github.workspace}}/vcpkg
          # Since the cache must be invalidated when content of the response file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{hashFiles(env.vcpkgResponseFile)}}

      - name: CMake
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          buildDirectory: ${{runner.workspace}}/out/build
          cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=${{matrix.buildType}} '

      - name: List build directory
        run: ls ${{runner.workspace}}/out/build/

      - name: Run native tests
        run: ${{matrix.displayWrapper || ''}} ${{runner.workspace}}/out/build/angle_easy_tests

      # The classpath separator character is different on Windows (;) versus other platforms (:). One way to avoid
      # using it is to pass * as the classpath, which causes java to put all .jar files in a directory in the classpath.
      # This requires avoiding bash's globbing, which would substitute the * before java saw it.
      #
      # Java puts the current working directory on java.library.path by default on Windows and Linux but not OSX so
      # set it explicitly.
      - name: Run Java tests
        run: |
          set -o noglob
          ${{matrix.displayWrapper || ''}} java -cp * -Djava.library.path=. JavaSmokeTest
        shell: bash
        working-directory: ${{runner.workspace}}/out/build

      - name: Upload android.opengl JAR file
        uses: actions/upload-artifact@v2
        if: ${{matrix.uploadArtifact}}
        with:
          name: android.opengl-${{matrix.arch}}-${{matrix.os}}
          path: ${{runner.workspace}}/out/build/android.opengl.jar

      - name: Upload android.opengl native shared library
        uses: actions/upload-artifact@v2
        if: ${{matrix.uploadArtifact}}
        with:
          name: android.opengl-${{matrix.arch}}-${{matrix.os}}
          path: ${{runner.workspace}}/out/build/${{matrix.soPrefix}}android.opengl.${{matrix.soExtension}}


  package:
    name: Package android.opengl
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{runner.workspace}}/out/build

      - name: List artifacts directory
        run: ls ${{runner.workspace}}/out/build
